'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname,'../js/db-service.js'),'utf8');
const service = new Function('db','window',source+'\nreturn DBService;')({},{});
const token = service.getPayslipReceiptToken;
const gv = { role:'giao-vien', netPay:400000, stats:{workedShifts:3,vpShifts:1} };
const tt = { role:'tiep-tan', netPay:100000 };
const old = {role:'dual',status:'published',status_gv:'published',status_tt:'draft',details_gv:gv,details_tt:tt};
const newlyPublished = {...old,status_tt:'published'};
assert.notEqual(token(old),token(newlyPublished),'new unseen component changes receipt token');
assert.notEqual(token(old),token({...old,details_gv:{...gv,netPay:500000}}),'changed amount changes token');
assert.equal(token(newlyPublished),token({...newlyPublished,status:'received',status_gv:'received',status_tt:'received',receivedAt:'now'}),'repeat receipt is idempotent');
assert.equal(token(old),token({...old,details_gv:{stats:{vpShifts:1,workedShifts:3},netPay:400000,role:'giao-vien'}}),'Firestore map ordering must not change token');
assert.equal(service.getPayslipLifecycleState({role:'dual',status:'published',details_gv:gv,details_tt:tt}).status_tt,'published','legacy TT export uses shared lifecycle');
const report=fs.readFileSync(path.join(__dirname,'../js/report.js'),'utf8');
const payload=report.slice(report.indexOf('function getCurrentCalculationPayload'),report.indexOf('async function saveCalculationDraftToDb'));
assert.match(payload,/window\.unfilteredAllMonthChips \|\| window\.currentMonthChips/);
assert.match(payload,/chip\.isAbsence \|\| chip\.absenceType/);
assert.match(report,/currentMonthlySalarySettingsAll\[roleKey\] = \{ \.\.\.loadedSettings, \.\.\.settingsObj \}/);
assert.match(report,/rowData\.manual !== true/);
const chartSource=fs.readFileSync(path.join(__dirname,'../js/chart-service.js'),'utf8');
const chart=new Function('DBService','isAssignedToClass',chartSource+'\nreturn ChartService;')({},(cls,id)=>cls.gvId===id);
const future=new Date(Date.now()+3600000);
const date=`${future.getFullYear()}-${String(future.getMonth()+1).padStart(2,'0')}-${String(future.getDate()).padStart(2,'0')}`;
const time=`${String(future.getHours()).padStart(2,'0')}:${String(future.getMinutes()).padStart(2,'0')}`;
assert.equal(chart.getStaffPunctuality([],{[date]:{evening1:[{gvId:'staff',start:time,end:'23:59'}]}},'staff').absent,0);
console.log('payroll-sync.test.js: canonical source, rate preservation, absence metadata, manual bonus, receipt tokens and legacy lifecycle passed');
